export const certificadosData = [
    {
        id: 1,
        data: "Abr 2024",
        titulo: "HTMl - CSS - JavaScript",
        imagem: "/assets/certificados/html-css-js.png",
    },
    {
        id: 2,
        data: "Mai 2024",
        titulo: "Firebase - Jquery - Bootstrap",
        imagem: "/assets/certificados/firebase-botstrap.png",
    },
    {
        id: 3,
        data: "Mai 2024",
        titulo: "Python",
        imagem: "/assets/certificados/python.png",
    },
    {
        id: 4,
        data: "Jun 2024",
        titulo: "Power BI",
        imagem: "/assets/certificados/powerbi.png",
    },
    {
        id: 5,
        data: "Jul 2024",
        titulo: "NodeJs - MongoDb",
        imagem: "/assets/certificados/nodejs-mongobd.png",
    },
    {
        id: 6,
        data: "Jul 2024",
        titulo: "React",
        imagem: "/assets/certificados/react.png",
    },
    {
        id: 7,
        data: "Jul 2024",
        titulo: "Excel",
        imagem: "/assets/certificados/excel.png",
    },
    {
        id: 8,
        data: "Set 2024",
        titulo: "SQL",
        imagem: "/assets/certificados/sql.png",
    },
    {
        id: 9,
        data: "Out 2024",
        titulo: "Figma",
        imagem: "/assets/certificados/figma.png",
    },
    {
        id: 10,
        data: "Dez 2024",
        titulo: "NLW Mobile",
        imagem: "/assets/certificados/nlwMobile.png",
    },
    {
        id: 11,
        data: "Jan 2025",
        titulo: "Clean Code",
        imagem: "/assets/certificados/cleancode.png",
    },
    {
        id: 12,
        data: "Jan 2025",
        titulo: "Tailwind",
        imagem: "/assets/certificados/tailwind.png",
    },
     {
        id: 13,
        data: "Fev 2025",
        titulo: "NLW Nodejs",
        imagem: "/assets/certificados/nlwBackEnd.png",
    },
     {
        id: 14,
        data: "Mai 2025",
        titulo: "Figma",
        imagem: "/assets/certificados/ui-ux.png",
    },
     {
        id: 15,
        data: "Set 2025",
        titulo: "Saas",
        imagem: "/assets/certificados/saas.png",
    },
     {
        id: 16,
        data: "Jan 2026",
        titulo: "Fundamentos NextJs",
        imagem: "/assets/certificados/fundamento-next.png",
    },
     {
        id: 17,
        data: "Fev 2026",
        titulo: "NextJs - PetShop",
        imagem: "/assets/certificados/next2.png",
    },
    {
        id: 18,
        data: "Fev 2026",
        titulo: "NextJs - PetShop",
        imagem: "/assets/certificados/next3.png",
    },
    {
        id: 19,
        data: "Fev 2026",
        titulo: "NextJs - BoardApp",
        imagem: "/assets/certificados/next.png",
    },
    {
        id: 20,
        data: "Jun 2026",
        titulo: "SQL - Postgres",
        imagem: "/assets/certificados/postgres.png",
    },
];